# ===============================
# DATABASE CONFIG
# ===============================

spring.datasource.url=jdbc:postgresql://ep-dark-unit-aob4jvo6.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_pwfjV0La5BRl

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rutvikdevdare@gmail.com
spring.mail.password=dpay msun foig uzej

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
openrouter.api.key=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